# Generated by Django 4.2.11 on 2025-12-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('type_vehicule', models.CharField(blank=True, max_length=100)),
                ('capacite_charge', models.DecimalField(blank=True, decimal_places=2, help_text='Capacité en kg', max_digits=10, null=True)),
                ('consommation', models.DecimalField(blank=True, decimal_places=2, help_text='L/100km', max_digits=5, null=True)),
                ('etat', models.CharField(blank=True, default='disponible', max_length=40)),
                ('date_mise_service', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
            },
        ),
    ]
