# Generated by Django 4.2.11 on 2025-12-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_vehicule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='id_vehicule',
            field=models.CharField(editable=False, max_length=12, primary_key=True, serialize=False),
        ),
    ]
