# Generated by Django 4.2.11 on 2025-12-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_alter_vehicule_id_vehicule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express'), ('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
