# Generated by Django 4.2.11 on 2025-12-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='type',
        ),
        migrations.AddField(
            model_name='service',
            name='speed',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='zone',
            field=models.CharField(choices=[('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], default='NATIONAL', max_length=20),
        ),
    ]
