# Generated by Django 4.2.11 on 2025-12-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_service_type_service_speed_service_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
    ]
