# Generated by Django 4.2.11 on 2025-12-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='password_client',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
