# Generated by Django 4.2.11 on 2025-12-31 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_client_password_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chauffeur',
            fields=[
                ('id_chauffeur', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('password_driver', models.CharField(help_text='Mot de passe du chauffeur (haché)', max_length=128)),
                ('nom', models.CharField(max_length=150)),
                ('prenom', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('numero_permis', models.CharField(max_length=50, unique=True, verbose_name='Numéro de permis')),
                ('date_embauche', models.DateField(auto_now_add=True)),
                ('disponibilite', models.BooleanField(default=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('suspendu', 'Suspendu'), ('en_conge', 'En congé')], default='actif', max_length=20)),
            ],
            options={
                'verbose_name': 'Chauffeur',
                'verbose_name_plural': 'Chauffeurs',
            },
        ),
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id_expedition', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=150)),
                ('destination', models.CharField(max_length=150)),
                ('kilometrage', models.DecimalField(decimal_places=2, help_text='Distance en kilomètres', max_digits=8)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expeditions', to='database.client')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='database.chauffeur')),
            ],
            options={
                'verbose_name': 'Expedition',
                'verbose_name_plural': 'Expeditions',
            },
        ),
    ]
