# Generated by Django 6.0 on 2026-01-01 14:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_chauffeur_expedition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id_reclamation', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Reclamation ID')),
                ('date_reclamation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Reclamation Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('nature', models.CharField(max_length=255, verbose_name='Nature')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled'), ('pending_customer', 'Pending Customer Response'), ('closed', 'Closed')], default='new', max_length=50, verbose_name='Status')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
            ],
            options={
                'verbose_name': 'Réclamation',
                'verbose_name_plural': 'Réclamations',
                'db_table': 'reclamation',
                'ordering': ['-date_reclamation'],
            },
        ),
    ]
