# Generated by Django 6.0 on 2026-01-01 14:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_reclamation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id_incident', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Incident ID')),
                ('incident_type', models.CharField(choices=[('delay', 'Delay'), ('loss', 'Package Loss'), ('damage', 'Damage'), ('technical', 'Technical Problem'), ('accident', 'Accident'), ('other', 'Other')], max_length=50, verbose_name="Type d'incident")),
                ('description', models.TextField(verbose_name='Description')),
                ('incident_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Date de l'incident")),
                ('status', models.CharField(choices=[('new', 'New'), ('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='new', max_length=50, verbose_name='Status')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='incidents/attachments/', verbose_name='Document ou photo joint')),
                ('commentaire', models.TextField(blank=True, verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('resolution_date', models.DateTimeField(blank=True, null=True, verbose_name='Resolution Date')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Incident',
                'verbose_name_plural': 'Incidents',
                'db_table': 'incident',
                'ordering': ['-incident_date'],
            },
        ),
    ]
