# Generated by Django 6.0 on 2026-01-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_incident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, verbose_name='Agent ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('mot_de_passe', models.CharField(max_length=255, verbose_name='Mot de passe (hashé)')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('agent', 'Agent Transport')], default='agent', max_length=50, verbose_name='Rôle')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('date_embauche', models.DateField(blank=True, null=True, verbose_name="Date d'embauche")),
                ('est_actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agent',
                'ordering': ['nom', 'prenom'],
            },
        ),
    ]
