# Generated by Django 6.0 on 2026-01-04 09:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_agent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id_package', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('number_of_pieces', models.PositiveIntegerField()),
                ('package_type', models.CharField(choices=[('DOC', 'Documents'), ('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('OTHER', 'Other')], max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='database.client')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id_shipment', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('zone', models.CharField(choices=[('NATIONAL', 'National'), ('INTERNATIONAL', 'International')], max_length=20)),
                ('speed', models.CharField(choices=[('NORMAL', 'Normal'), ('EXPRESS', 'Express')], max_length=20)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('package', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipment', to='database.package')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id_invoice', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('invoice_date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_pdf', models.FileField(upload_to='invoices/')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='database.client')),
                ('shipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice', to='database.shipment')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False)),
                ('tour_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tours', to='database.chauffeur')),
                ('shipments', models.ManyToManyField(blank=True, related_name='tours', to='database.shipment')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
            },
        ),
    ]
