# Generated by Django 4.2.11 on 2026-01-11 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0012_package_shipment_invoice_tour'),
    ]

    operations = [
        migrations.AddField(
            model_name='chauffeur',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chauffeurs', to='database.vehicule'),
        ),
    ]
