# Generated by Django 6.0 on 2026-01-23 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0014_migrate_expedition_to_shipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agent',
            options={},
        ),
        migrations.RemoveField(
            model_name='agent',
            name='derniere_connexion',
        ),
        migrations.AlterField(
            model_name='agent',
            name='est_actif',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(blank=True, help_text='Optional: client linked to this shipment (duplicate of package.client)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='database.client'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='kilometrage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Distance in kilometers (optional)', max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='statut',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered')], default='PENDING', max_length=20),
        ),
        migrations.AlterModelTable(
            name='agent',
            table=None,
        ),
    ]
